# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TSi - Technical Solutions Inc.
email: sales@techsol.ca
description: > # this means to ignore newlines until "baseurl:"
 Canadian Smart Lighting is your premier provider of comfort and security enhancing yard lighting through the use of smart design and smart features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bempey.github.io/Testing_Jeckyll_TSi" # the base hostname & protocol for your site
twitter_username: brianempey
github_username:  bempey

# Build settings 
markdown: kramdown 
theme: minima 
plugins_dir: 
  - jekyll-feed 

defaults: 
  - 
    scope: 
       path: ""
       type: "posts"
    values: 
          layout: "post" 
          title: "My Title for Posts" 
